---
title: "HW5"
author: "Aditya"
date: "December 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#####Q1
```{r}
df <- read.csv("C:/Users/garapati/Desktop/MSDS_DDS/week5/yob2016.txt",header=F,sep = ";")
names(df) <- c("Name","Sex","count")
head(df)
str(df)
grep("yyy$", df$Name)
y2016 <- df[-212,]
y2016[212,]
```
####Q2
```{r}
df <- read.csv("C:/Users/garapati/Desktop/MSDS_DDS/week5/yob2015.txt",header=FALSE)
names(df) <- c("Name","Sex","count")
tail(df)
y2015 <- df

final1 <-merge(y2015, y2016, by="Name", all = TRUE)
apply(final1, 2, function(x) any(is.na(x) | is.infinite(x)))
final <-na.omit(final1)
apply(final, 2, function(x) any(is.na(x) | is.infinite(x)))
head(final)
```
####Q3
```{r}
temp <- c(final$count.x+final$count.y)
final$count <- paste(temp)
library("hablar")
final <- convert(final,num(count.x,count.y,count))
head(final)
final <- final[order(final$count),]
gals <- subset(final,(final$Sex.y == "F"))
t1 <- tail(gals,10) 
write.csv(t1$Name,"name.csv")
```


